info.app.name: tuscan.pro
info.app.description: Faceit CS:GO Player Stats Analyzer
info.app.version: 1.0.0

faceit-matches:
  cutoff-date-timestamp: 1410282903

faceit:
  timeout:
    read: 3500
    connect: 1000
  retry:
    min-backoff: 300
    max-backoff: 600
    max-retries: 2

server:
  port: 8080

management:
  metrics:
    export:
      graphite:
        enabled: false

mongoClientProperties:
  socketTimeout: 1000
  connectionsPerHost: 100
